// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pressAgency.Domain.Context;

#nullable disable

namespace pressAgency.Domain.Migrations
{
    [DbContext(typeof(PressDbContext))]
    [Migration("20260118163138_seederAdded")]
    partial class seederAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("pressAgency.Domain.Entites.Authors", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("AuthorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            Email = "john.doe@netpress.com",
                            Name = "John Doe"
                        },
                        new
                        {
                            AuthorId = 2,
                            Email = "redaction@netpress.com",
                            Name = "Redaction Team"
                        });
                });

            modelBuilder.Entity("pressAgency.Domain.Entites.Posts", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PostId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            AuthorId = 1,
                            Content = "PostgreSQL is a powerful open-source relational database known for reliability, extensibility, and strong SQL compliance.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Introduction to PostgreSQL",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 2,
                            AuthorId = 2,
                            Content = "Indexes help databases retrieve data faster by reducing the number of scanned rows during query execution.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Understanding Indexes",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 3,
                            AuthorId = 1,
                            Content = "ACID stands for Atomicity, Consistency, Isolation, and Durability, which guarantee reliable database transactions.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "ACID Properties Explained",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 4,
                            AuthorId = 2,
                            Content = "Normalization reduces data redundancy and improves data integrity by organizing tables and relationships.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Database Normalization Basics",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 5,
                            AuthorId = 1,
                            Content = "Multi-Version Concurrency Control allows PostgreSQL to handle concurrent reads and writes efficiently.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "What Is MVCC",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 6,
                            AuthorId = 2,
                            Content = "Transactions group multiple operations into a single unit of work that either fully succeeds or fails.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Transactions in Practice",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 7,
                            AuthorId = 1,
                            Content = "Foreign keys enforce referential integrity between related tables and prevent invalid data relationships.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Using Foreign Keys",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 8,
                            AuthorId = 2,
                            Content = "Soft deletes keep data for auditing while hard deletes permanently remove records from the database.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Soft Deletes vs Hard Deletes",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 9,
                            AuthorId = 1,
                            Content = "REST APIs use standard HTTP methods to enable communication between clients and servers.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "REST API Fundamentals",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 10,
                            AuthorId = 2,
                            Content = "Status codes indicate the result of an HTTP request and help clients understand server responses.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "HTTP Status Codes Overview",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 11,
                            AuthorId = 1,
                            Content = "JSON Web Tokens are commonly used for stateless authentication between clients and APIs.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "JWT Authentication",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 12,
                            AuthorId = 2,
                            Content = "Sessions can be managed using cookies, server-side storage, or token-based approaches.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Session Management Strategies",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 13,
                            AuthorId = 1,
                            Content = "Migrations help evolve database schemas in a controlled and versioned manner.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Database Migrations",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 14,
                            AuthorId = 2,
                            Content = "Query optimization involves proper indexing, query rewriting, and understanding execution plans.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Optimizing SQL Queries",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 15,
                            AuthorId = 1,
                            Content = "Pagination limits result sets to improve performance and user experience in data-heavy applications.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Pagination Techniques",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 16,
                            AuthorId = 2,
                            Content = "Partitioning and indexing strategies help maintain performance when working with large datasets.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Handling Large Tables",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 17,
                            AuthorId = 1,
                            Content = "Consistent error handling improves debuggability and resilience of backend services.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Error Handling Best Practices",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 18,
                            AuthorId = 2,
                            Content = "Effective logging and monitoring provide insight into system health and production issues.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Logging and Monitoring",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 19,
                            AuthorId = 1,
                            Content = "Race conditions and deadlocks can occur when multiple processes access shared resources.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Concurrency Issues",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 20,
                            AuthorId = 2,
                            Content = "Regular backups protect against data loss and enable disaster recovery.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Database Backups",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 21,
                            AuthorId = 1,
                            Content = "EXPLAIN ANALYZE shows how PostgreSQL executes a query and where performance bottlenecks exist.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Using EXPLAIN ANALYZE",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 22,
                            AuthorId = 2,
                            Content = "Connection pooling improves performance by reusing database connections instead of creating new ones.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Connection Pooling",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 23,
                            AuthorId = 1,
                            Content = "Caching frequently accessed data reduces database load and improves response times.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Caching Strategies",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 24,
                            AuthorId = 2,
                            Content = "Good schema design balances normalization, performance, and future scalability.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Schema Design Principles",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 25,
                            AuthorId = 1,
                            Content = "Principle of least privilege, encryption, and validation help secure applications and data.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Security Best Practices",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PostId = 26,
                            AuthorId = 2,
                            Content = "Production readiness includes monitoring, backups, performance testing, and security reviews.",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Preparing for Production",
                            UpdatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("pressAgency.Domain.Entites.PostsLock", b =>
                {
                    b.Property<int>("PostLockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostLockId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LockExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("PostLockId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("PostsLocks");
                });

            modelBuilder.Entity("pressAgency.Domain.Entites.Posts", b =>
                {
                    b.HasOne("pressAgency.Domain.Entites.Authors", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("pressAgency.Domain.Entites.PostsLock", b =>
                {
                    b.HasOne("pressAgency.Domain.Entites.Authors", "Author")
                        .WithMany("PostsLocks")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pressAgency.Domain.Entites.Posts", "Post")
                        .WithMany("PostsLocks")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("pressAgency.Domain.Entites.Authors", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("PostsLocks");
                });

            modelBuilder.Entity("pressAgency.Domain.Entites.Posts", b =>
                {
                    b.Navigation("PostsLocks");
                });
#pragma warning restore 612, 618
        }
    }
}
